### ISSUE TITLE
Не хватает Docker образа

### ISSUE THREAD

**Issue by klpx** [pashabezborod/deeplayTest#2]
Я бы хотел попробовать ваше приложение, но у меня не получается поставить Java да и вообще непонятно какую версию ставить.
Не могли бы создать Dockerfile, собрать и опубликовать образ. Чтобы я мог просто запустить `docker run -v $(pwd):/input pashabezborod/deeplay` и получить нужные мне ответы, не заморачиваясь с установкой JDK и сборкой приложения.

**Comment by pashabezborod** [comment]
Всё готово к использованию с Docker
